[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "object_detection_training"
version = "0.0.1"
description = "Object detector training project using rfnet and hydra"
authors = [{name = "Enrique G. Ortiz", email = "ortizeg@gmail.com"}]
dependencies = [
    "hydra-core",
    "tensorboard",
    "rfdetr",
]

[tool.black]
line-length = 88
target-version = ['py311']
include = '\.pyi?$'

[tool.isort]
profile = "black"
